// @title Order Management API
// @version 1.0
// @description This is a sample API for order management
// @host localhost:8080
// @BasePath /api
package main

import (
	"log"
	"order-manage/cmd/config"
	"order-manage/controllers"
	"order-manage/middleware"
	"order-manage/repository"
	"order-manage/usecase"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"

	_ "order-manage/docs" // Import docs generated by Swag

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	err := godotenv.Load(".env")
	if err != nil {
		log.Fatalf("Error loading .env file")
	}

	db := config.ConnectDataBase()
	userRepository := repository.NewUserRepository(db)
	customerRepository := repository.NewCustomerRepository(db)
	authUsecase := usecase.NewAuthUsecase(userRepository)
	userUsecase := usecase.NewUserUsecase(userRepository)
	customerUsecase := usecase.NewCustomerUsecase(customerRepository)
	controllers := controllers.Handler{
		AuthUsecase:     authUsecase,
		UserUsecase:     userUsecase,
		CustomerUsecase: customerUsecase,
	}

	r := gin.Default()

	// Route untuk Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	public := r.Group("/api")
	public.POST("/register", controllers.Register)
	public.POST("/login", controllers.Login)

	protected := r.Group("/api/user")
	protected.Use(middleware.JwtAuthMiddleware())
	protected.GET("/profile", controllers.GetProfile)

	protectedCust := r.Group("/api/customer")
	protectedCust.Use(middleware.JwtAuthMiddleware())
	protectedCust.POST("", controllers.SaveCustomer)
	protectedCust.PUT("/:id", controllers.UpdateCustomer)
	protectedCust.GET("/list", controllers.GetCustomers)
	protectedCust.GET("/:id", controllers.GetCustomerByID)

	r.Run(":8080")

}
